apiVersion: apps/v1
kind: Deployment
metadata:
  name: jspapi-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jspapi-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: wilconsadocker/jspringapirest:@@VERSION@@
        ports:
        - containerPort: 8080
#      nodeName: wnode2
---
apiVersion: v1
kind: Service
metadata:
  name: jspapi-lb
spec:
  type: LoadBalancer
  selector:
    app: jspapi-app
  ports:
    - protocol: TCP
      port: 8080
# externalTrafficPolicy: Local